services:
  - type: web
    name: ligaprof7-v32-pwa
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/server.py
    envVars:
      - key: PORT
        value: 10000
